# Processos Feitos Anterioremente

In [3]:
import numpy as np
import pickle

with open('credit.pkl', 'rb') as f:
    x_credit_treinamento, y_credit_treinamento, x_credit_teste, y_credit_teste = pickle.load(f)

In [4]:
x_credit = np.concatenate((x_credit_treinamento, x_credit_teste), axis=0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis=0)

# Carregar um Classificador já Treinado

In [2]:
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

### Pegando a primeira linha do dataset x_credit

In [8]:
novo_registro = x_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

### Mudando o formato do array.

In [9]:
novo_registro = novo_registro.reshape(1, -1)
novo_registro

array([[-1.3754462 ,  0.50631087,  0.10980934]])

### Prevendo o resultado com os modelos treinados

In [10]:
rede_neural.predict(novo_registro)

array([0], dtype=int64)

In [11]:
arvore.predict(novo_registro)

array([0], dtype=int64)

In [12]:
svm.predict(novo_registro)

array([0], dtype=int64)